import { v4 as uuid } from "uuid";

export const initialProducts = [
  {
    id: uuid(),
    name: "محصول اول",
    img: "productImg__1",
    categori: "free",
    price: 0,
    description: "رایگان",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول دوم",
    img: "productImg__2",
    categori: "mostSale",
    price: 400,
    description: "پرفروش ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول سوم",
    img: "productImg__3",
    categori: "mostVisit",
    price: 450,
    description: "پربازدید ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول چهارم",
    img: "productImg__4",
    categori: "hasOff",
    price: 250,
    description: "دارای تخفیف",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول پنجم",
    img: "productImg__5",
    categori: "mostExpensive",
    price: 750,
    description: "گران ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول ششم",
    img: "productImg__6",
    categori: "free",
    price: 0,
    description: "رایگان",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول هفتم",
    img: "productImg__7",
    categori: "mostSale",
    price: 400,
    description: "پرفروش ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول هشتم",
    img: "productImg__8",
    categori: "mostVisit",
    price: 450,
    description: "پربازدید ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول نهم",
    img: "productImg__9",
    categori: "hasOff",
    price: 250,
    description: "دارای تخفیف",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول دهم",
    img: "productImg__10",
    categori: "mostExpensive",
    price: 750,
    description: "گران ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول یازدهم",
    img: "productImg__11",
    categori: "free",
    price: 0,
    description: "رایگان",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول دوازدهم",
    img: "productImg__12",
    categori: "mostSale",
    price: 400,
    description: "پرفروش ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول سیزدهم",
    img: "productImg__13",
    categori: "mostVisit",
    price: 450,
    description: "پربازدید ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول چهاردهم",
    img: "productImg__14",
    categori: "hasOff",
    price: 250,
    description: "دارای تخفیف",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول پانزدهم",
    img: "productImg__15",
    categori: "mostExpensive",
    price: 750,
    description: "گران ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول شانزدهم",
    img: "productImg__16",
    categori: "free",
    price: 0,
    description: "رایگان",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول هفدهم",
    img: "productImg__17",
    categori: "mostSale",
    price: 400,
    description: "پرفروش ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول هجدهم",
    img: "productImg__18",
    categori: "mostVisit",
    price: 450,
    description: "پربازدید ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول نوزدهم",
    img: "productImg__19",
    categori: "hasOff",
    price: 250,
    description: "دارای تخفیف",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول بیستم",
    img: "productImg__20",
    categori: "mostExpensive",
    price: 750,
    description: "گران ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول بیست و یکم",
    img: "productImg__21",
    categori: "hasOff",
    price: 250,
    description: "دارای تخفیف",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول بیست و دوم",
    img: "productImg__22",
    categori: "free",
    price: 0,
    description: "رایگان",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول بیست و سوم",
    img: "productImg__23",
    categori: "mostSale",
    price: 400,
    description: "پرفروش ترین",
    count: 0,
  },
];
