import { v4 as uuid } from "uuid";

export const initialProducts = [
  {
    id: uuid(),
    name: "محصول 1",
    img: "productImg__1",
    categori: "free",
    price: 0,
    description: "رایگان",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 2",
    img: "productImg__2",
    categori: "mostSale",
    price: 400,
    description: "پرفروش ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 3",
    img: "productImg__3",
    categori: "mostVisit",
    price: 450,
    description: "پربازدید ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 4",
    img: "productImg__4",
    categori: "hasOff",
    price: 250,
    description: "دارای تخفیف",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 5",
    img: "productImg__5",
    categori: "mostExpensive",
    price: 750,
    description: "گران ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 6",
    img: "productImg__6",
    categori: "free",
    price: 0,
    description: "رایگان",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 7",
    img: "productImg__7",
    categori: "mostSale",
    price: 400,
    description: "پرفروش ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 8",
    img: "productImg__8",
    categori: "mostVisit",
    price: 450,
    description: "پربازدید ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 9",
    img: "productImg__9",
    categori: "hasOff",
    price: 250,
    description: "دارای تخفیف",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 10",
    img: "productImg__10",
    categori: "mostExpensive",
    price: 750,
    description: "گران ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 11",
    img: "productImg__11",
    categori: "free",
    price: 0,
    description: "رایگان",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 12",
    img: "productImg__12",
    categori: "mostSale",
    price: 400,
    description: "پرفروش ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 13",
    img: "productImg__13",
    categori: "mostVisit",
    price: 450,
    description: "پربازدید ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 14",
    img: "productImg__14",
    categori: "hasOff",
    price: 250,
    description: "دارای تخفیف",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 15",
    img: "productImg__15",
    categori: "mostExpensive",
    price: 750,
    description: "گران ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 16",
    img: "productImg__16",
    categori: "free",
    price: 0,
    description: "رایگان",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 17",
    img: "productImg__17",
    categori: "mostSale",
    price: 400,
    description: "پرفروش ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 18",
    img: "productImg__18",
    categori: "mostVisit",
    price: 450,
    description: "پربازدید ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 19",
    img: "productImg__19",
    categori: "hasOff",
    price: 250,
    description: "دارای تخفیف",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 20",
    img: "productImg__20",
    categori: "mostExpensive",
    price: 750,
    description: "گران ترین",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 21",
    img: "productImg__21",
    categori: "hasOff",
    price: 250,
    description: "دارای تخفیف",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 22",
    img: "productImg__22",
    categori: "free",
    price: 0,
    description: "رایگان",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 23",
    img: "productImg__23",
    categori: "mostSale",
    price: 400,
    description: "پرفروش ترین",
    count: 0,
  },
];
