import { v4 as uuid } from "uuid";

export const initialProducts = [
  {
    id: uuid(),
    name: "محصول 1",
    img: "productImg__1",
    category: "free",
    price: 0,
    description: "محصول نمونه 1",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 2",
    img: "productImg__2",
    category: "mostSale",
    price: 400,
    description: "محصول نمونه 2",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 3",
    img: "productImg__3",
    category: "mostVisit",
    price: 450,
    description: "محصول نمونه 3",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 4",
    img: "productImg__4",
    category: "hasOff",
    price: 250,
    description: "محصول نمونه 4",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 5",
    img: "productImg__5",
    category: "mostExpensive",
    price: 750,
    description: "محصول نمونه 5",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 6",
    img: "productImg__6",
    category: "free",
    price: 0,
    description: "محصول نمونه 6",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 7",
    img: "productImg__7",
    category: "mostSale",
    price: 400,
    description: "محصول نمونه 7",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 8",
    img: "productImg__8",
    category: "mostVisit",
    price: 450,
    description: "محصول نمونه 8",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 9",
    img: "productImg__9",
    category: "hasOff",
    price: 250,
    description: "محصول نمونه 9",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 10",
    img: "productImg__10",
    category: "mostExpensive",
    price: 750,
    description: "محصول نمونه 10",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 11",
    img: "productImg__11",
    category: "free",
    price: 0,
    description: "محصول نمونه 11",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 12",
    img: "productImg__12",
    category: "mostSale",
    price: 400,
    description: "محصول نمونه 12",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 13",
    img: "productImg__13",
    category: "mostVisit",
    price: 450,
    description: "محصول نمونه 13",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 14",
    img: "productImg__14",
    category: "hasOff",
    price: 250,
    description: "محصول نمونه 14",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 15",
    img: "productImg__15",
    category: "mostExpensive",
    price: 750,
    description: "محصول نمونه 15",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 16",
    img: "productImg__16",
    category: "free",
    price: 0,
    description: "محصول نمونه 16",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 17",
    img: "productImg__17",
    category: "mostSale",
    price: 400,
    description: "محصول نمونه 17",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 18",
    img: "productImg__18",
    category: "mostVisit",
    price: 450,
    description: "محصول نمونه 18",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 19",
    img: "productImg__19",
    category: "hasOff",
    price: 250,
    description: "محصول نمونه 19",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 20",
    img: "productImg__20",
    category: "mostExpensive",
    price: 750,
    description: "محصول نمونه 20",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 21",
    img: "productImg__21",
    category: "hasOff",
    price: 250,
    description: "محصول نمونه 21",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 22",
    img: "productImg__22",
    category: "free",
    price: 0,
    description: "محصول نمونه 22",
    count: 0,
  },
  {
    id: uuid(),
    name: "محصول 23",
    img: "productImg__23",
    category: "mostSale",
    price: 400,
    description: "محصول نمونه 23",
    count: 0,
  },
];
